# -*- coding: utf-8 -*-
"""training_resnet18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fXzUMjYzqRkuBgjCzkadBJVEsW4Q6n0
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
from torch.utils.data import DataLoader, Subset # WeightedRandomSampler available if class imbalance arises
import os
import time
import copy
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, f1_score, cohen_kappa_score
# from sklearn.model_selection import StratifiedKFold
import numpy as np
import multiprocessing
import random
import pickle
import json

# Try to import DirectML for AMD GPUs
try:
    import torch_directml
    dml_available = True
except ImportError:
    dml_available = False

# ----------------------------
# CONFIGURATION
# ----------------------------
CONFIG = {
    'batch_size': 48,
    'num_epochs': 15,
    'input_size': 224,
    'patience': 5,
    'num_folds': 3,
    'save_path': 'fruit_resnet18_model.pth',
    'data_dir': 'dataset'
}

def seed_worker(worker_id):
    np.random.seed(42 + worker_id)

def set_seed(seed=42):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def get_device():
    """Checks for available devices (CUDA -> DirectML -> CPU)."""
    if torch.cuda.is_available():
        print(f"✅ NVIDIA GPU Detected: {torch.cuda.get_device_name(0)}")
        return torch.device("cuda")
    elif dml_available:
        print("✅ AMD GPU Detected (via DirectML)")
        return torch_directml.device()
    else:
        print("⚠️ No GPU detected. Training on CPU will be slow.")
        return torch.device("cpu")

def plot_confusion_matrix(y_true, y_pred, classes):
    """Generates and saves a confusion matrix heatmap."""
    try:
        cm = confusion_matrix(y_true, y_pred)
        plt.figure(figsize=(14, 12))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                    xticklabels=classes, yticklabels=classes)
        plt.ylabel('Actual')
        plt.xlabel('Predicted')
        plt.title('Confusion Matrix — ResNet18')
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.savefig('confusion_matrix_resnet18.png')
        print("📊 Confusion Matrix saved to confusion_matrix_resnet18.png")
    except Exception as e:
        print(f"⚠️ Could not generate confusion matrix: {e}")

def plot_history(history, fold=None):
    suffix = f'_fold{fold}' if fold is not None else ''
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(history['train_loss'], label='Train Loss')
    plt.plot(history['val_loss'],   label='Val Loss')
    plt.title(f'Loss{" — Fold " + str(fold) if fold else ""}')
    plt.legend(); plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(history['train_acc'], label='Train Acc')
    plt.plot(history['val_acc'],   label='Val Acc')
    plt.title(f'Accuracy{" — Fold " + str(fold) if fold else ""}')
    plt.legend(); plt.grid(True)

    fname = f'training_results_resnet18{suffix}.png'
    plt.savefig(fname)
    plt.close()
    print(f"📊 Graph saved to {fname}")

def train_model(data_dir=CONFIG['data_dir']):
    set_seed(42)
    device = get_device()
    print(f"🚀 Training started on DEVICE: {device}")

    if not os.path.exists(data_dir):
        print(f"❌ Error: Directory '{data_dir}' not found.")
        return

    num_workers = min(4, multiprocessing.cpu_count())

    # ----------------------------
    # 1. ON-THE-FLY AUGMENTATION
    # ----------------------------
    # ColorJitter is intentionally kept here — ripeness classification is
    # heavily colour-dependent, so exposing the model to slight colour
    # variation during training improves generalisation without distorting
    # the discriminative signal.
    data_transforms = {
        'train': transforms.Compose([
            transforms.Resize((CONFIG['input_size'], CONFIG['input_size'])),
            transforms.RandomHorizontalFlip(p=0.5),
            transforms.ColorJitter(brightness=0.05, contrast=0.05,
                                   saturation=0.05, hue=0.02),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ]),
        'val': transforms.Compose([
            transforms.Resize((CONFIG['input_size'], CONFIG['input_size'])),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ]),
    }

    # ----------------------------
    # 2. LOAD DATA
    # ----------------------------
    print("📂 Loading dataset...")
    trainval_dir = os.path.join(data_dir, 'trainval')
    test_dir     = os.path.join(data_dir, 'test')

    if not os.path.exists(trainval_dir) or not os.path.exists(test_dir):
      print("❌ Expected 'trainval/' and 'test/' directories.")
      return

    trainval_dataset_aug = datasets.ImageFolder(trainval_dir, data_transforms['train'])
    trainval_dataset_val = datasets.ImageFolder(trainval_dir, data_transforms['val'])

    # Test set — held out, only evaluated once after CV
    test_dataset = datasets.ImageFolder(test_dir, data_transforms['val'])
    test_loader  = DataLoader(test_dataset, batch_size=CONFIG['batch_size'],
                              shuffle=False, num_workers=num_workers)

    classes     = trainval_dataset_aug.classes
    num_classes = len(classes)
    n_trainval = len(trainval_dataset_aug)

    print(f"✅ Classes         : {num_classes}")
    print(f"   Trainval pool : {n_trainval} images")
    print(f"   Test           : {len(test_dataset)} images")

    # ----------------------------
    # 3. 3-FOLD CROSS VALIDATION
    # ----------------------------
    with open("folds.pkl", "rb") as f:
      folds = pickle.load(f)

    fold_results     = []
    best_overall_acc = 0.0

    for fold, (train_idx, val_idx) in enumerate(folds):
        print(f"\n{'='*50}")
        print(f"  FOLD {fold+1}/{CONFIG['num_folds']}")
        print(f"{'='*50}")

        fold_train = Subset(trainval_dataset_aug, train_idx)
        fold_val   = Subset(trainval_dataset_val, val_idx)

        # Weighted sampler to handle class imbalance within this fold
        # fold_targets   = [all_targets[i] for i in train_idx]
        # class_counts   = np.bincount(fold_targets)
        # class_weights  = 1.0 / (class_counts + 1e-5)
        # sample_weights = [class_weights[t] for t in fold_targets]
        # sampler = WeightedRandomSampler(sample_weights, len(sample_weights), replacement=True)

        train_loader = DataLoader(fold_train, batch_size=CONFIG['batch_size'],
                                  shuffle=True, num_workers=num_workers,
                                  worker_init_fn=seed_worker)
        val_loader   = DataLoader(fold_val, batch_size=CONFIG['batch_size'],
                                  shuffle=False, num_workers=num_workers)

        dataloaders   = {'train': train_loader, 'val': val_loader}

        # ----------------------------
        # Fresh ResNet18 for each fold
        # 3-phase progressive unfreeze:
        #   Epochs 0–4  : FC head only       (lr = 1e-3)
        #   Epochs 5–9  : + layer4           (lr = 5e-4)
        #   Epochs 10+  : full backbone      (lr = 1e-4)
        # ----------------------------
        model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)

        for param in model.parameters():
            param.requires_grad = False

        num_ftrs = model.fc.in_features
        model.fc = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(num_ftrs, num_classes)
        )
        for param in model.fc.parameters():
            param.requires_grad = True

        model = model.to(device)
        scaler = torch.cuda.amp.GradScaler(enabled=(device.type == 'cuda'))

        criterion = nn.CrossEntropyLoss(label_smoothing=0.05)
        optimizer = optim.AdamW(model.fc.parameters(), lr=1e-3, weight_decay=1e-4)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=3)

        best_fold_acc      = 0.0
        best_fold_wts      = copy.deepcopy(model.state_dict())
        epochs_no_improve  = 0
        history            = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}
        freeze1_epochs     = 4   # unfreeze layer4
        freeze2_epochs     = 8  # unfreeze full backbone
        since              = time.time()

        for epoch in range(CONFIG['num_epochs']):

            if epoch == freeze1_epochs:
                # Phase 2: unfreeze layer4. Reset patience so the new lr
                # gets a full window (up to 8 epochs) before early stopping.
                print("\n  🔓 Unfreezing layer4...")
                for param in model.layer4.parameters():
                    param.requires_grad = True
                optimizer = optim.AdamW(
                    filter(lambda p: p.requires_grad, model.parameters()),
                    lr=5e-4, weight_decay=1e-4
                )
                scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=3)
                epochs_no_improve=0

            if epoch == freeze2_epochs:
                # Phase 3: unfreeze full backbone. Same patience reset rationale.
                print("\n  🔓 Unfreezing full backbone...")
                for param in model.parameters():
                    param.requires_grad = True
                optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
                scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=3)
                epochs_no_improve=0

            print(f'  Epoch {epoch+1}/{CONFIG["num_epochs"]}', end=' ')

            for phase in ['train', 'val']:
                model.train() if phase == 'train' else model.eval()
                running_loss, running_corrects = 0.0, 0

                n_seen = 0
                for inputs, labels in dataloaders[phase]:
                  inputs, labels = inputs.to(device), labels.to(device)

                  with torch.set_grad_enabled(phase == 'train'):
                    with torch.cuda.amp.autocast(enabled=(device.type == 'cuda')):
                      outputs = model(inputs)
                      _, preds = torch.max(outputs, 1)
                      loss = criterion(outputs, labels)
                    if phase == 'train':
                      optimizer.zero_grad()
                      scaler.scale(loss).backward()
                      scaler.step(optimizer)
                      scaler.update()

                  running_loss += loss.item() * inputs.size(0)
                  running_corrects += torch.sum(preds == labels.data)
                  n_seen += inputs.size(0)

                epoch_loss = running_loss / n_seen
                epoch_acc  = (running_corrects.double() / n_seen).item()

                if phase == 'train':
                    history['train_loss'].append(epoch_loss)
                    history['train_acc'].append(epoch_acc)
                    print(f"| Train Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}", end=' ')
                else:
                    history['val_loss'].append(epoch_loss)
                    history['val_acc'].append(epoch_acc)
                    print(f"| Val Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}")
                    scheduler.step(epoch_acc)
                    if epoch_acc > best_fold_acc:
                        best_fold_acc = epoch_acc
                        best_fold_wts = copy.deepcopy(model.state_dict())
                        epochs_no_improve = 0
                    else:
                        epochs_no_improve += 1

            if epochs_no_improve >= CONFIG['patience']:
                print(f"\n  ✋ Early stopping at epoch {epoch+1}")
                break

        elapsed = time.time() - since
        print(f"\n  ⏱ Fold {fold+1} done in {elapsed//60:.0f}m {elapsed%60:.0f}s")
        print(f"  🏅 Fold {fold+1} Best Val Acc: {best_fold_acc:.4f}")
        fold_results.append(best_fold_acc)
        plot_history(history, fold=fold+1)

        if best_fold_acc > best_overall_acc:
            best_overall_acc = best_fold_acc
        # NOTE: We do NOT save fold weights here.
        # The final model will be retrained on the full trainval set.

    # ----------------------------
    # 4. CROSS-VALIDATION SUMMARY
    # ----------------------------
    print(f"\n{'='*50}")
    print(f"  5-FOLD CV RESULTS — ResNet18")
    print(f"{'='*50}")
    for i, acc in enumerate(fold_results):
        print(f"  Fold {i+1}: {acc:.4f}")
    print(f"  Mean : {np.mean(fold_results):.4f} ± {np.std(fold_results):.4f}")
    print(f"  Best : {best_overall_acc:.4f}")

    # ----------------------------
    # 5. RETRAIN FINAL MODEL ON FULL TRAINVAL
    # ----------------------------
    # Option 1 CV protocol: CV was used only to validate hyperparameters.
    # The final model is now retrained from scratch on the FULL trainval set
    # using those fixed hyperparameters, then evaluated ONCE on the test set.
    print(f"\n🔁 Retraining final model on full trainval set...")
    full_loader = DataLoader(trainval_dataset_aug, batch_size=CONFIG['batch_size'],
                             shuffle=True, num_workers=num_workers,
                             worker_init_fn=seed_worker)
    final_model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
    for param in final_model.parameters():
      param.requires_grad = False
    num_ftrs = final_model.fc.in_features
    final_model.fc = nn.Sequential(
        nn.Dropout(0.5),
        nn.Linear(num_ftrs, num_classes)
    )
    for param in final_model.fc.parameters():
      param.requires_grad = True
    final_model = final_model.to(device)

    final_scaler    = torch.cuda.amp.GradScaler(enabled=(device.type == 'cuda'))
    final_criterion = nn.CrossEntropyLoss(label_smoothing=0.05)
    final_optimizer = optim.AdamW(final_model.fc.parameters(), lr=1e-3, weight_decay=1e-4)
    final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='max', factor=0.5, patience=3)

    best_final_acc = 0.0
    best_final_wts = copy.deepcopy(final_model.state_dict())
    final_history  = {'train_loss': [], 'train_acc': []}
    final_since    = time.time()

    for epoch in range(CONFIG['num_epochs']):
      if epoch == 4:
        print("\n  🔓 Unfreezing layer4...")
        for param in final_model.layer4.parameters():
          param.requires_grad = True
        final_optimizer = optim.AdamW(
            filter(lambda p: p.requires_grad, final_model.parameters()), lr=5e-4, weight_decay=1e-4)
        final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='max', factor=0.5, patience=3)

      if epoch == 8:
        print("\n  🔓 Unfreezing full backbone...")
        for param in final_model.parameters():
          param.requires_grad = True
        final_optimizer = optim.AdamW(final_model.parameters(), lr=1e-4, weight_decay=1e-4)
        final_scheduler = optim.lr_scheduler.ReduceLROnPlateau(final_optimizer, mode='max', factor=0.5, patience=3)

      final_model.train()
      running_loss, running_corrects, n_seen = 0.0, 0, 0
      print(f'  Final Epoch {epoch+1}/{CONFIG["num_epochs"]}', end=' ')

      for inputs, labels in full_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        with torch.cuda.amp.autocast(enabled=(device.type == 'cuda')):
          outputs = final_model(inputs)
          _, preds = torch.max(outputs, 1)
          loss = final_criterion(outputs, labels)
        final_optimizer.zero_grad()
        final_scaler.scale(loss).backward()
        final_scaler.step(final_optimizer)
        final_scaler.update()
        running_loss += loss.item() * inputs.size(0)
        running_corrects += torch.sum(preds == labels.data)
        n_seen += inputs.size(0)

      epoch_loss = running_loss / n_seen
      epoch_acc  = (running_corrects.double() / n_seen).item()
      final_history['train_loss'].append(epoch_loss)
      final_history['train_acc'].append(epoch_acc)
      print(f"| Train Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}")
      final_scheduler.step(epoch_acc)

      if epoch_acc > best_final_acc:
        best_final_acc = epoch_acc
        best_final_wts = copy.deepcopy(final_model.state_dict())

    elapsed = time.time() - final_since
    print(f"\n  ⏱ Final model trained in {elapsed//60:.0f}m {elapsed%60:.0f}s")
    final_model.load_state_dict(best_final_wts)

    # ----------------------------
    # 6. EVALUATE FINAL MODEL ON TEST SET (once)
    # ----------------------------
    print(f"\n🔬 Evaluating final model on held-out TEST set...")
    final_model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
      for inputs, labels in test_loader:
        inputs = inputs.to(device)
        outputs = final_model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    report = classification_report(all_labels, all_preds, target_names=classes)
    macro_f1 = f1_score(all_labels, all_preds, average='macro')
    weighted_f1 = f1_score(all_labels, all_preds, average='weighted')
    kappa = cohen_kappa_score(all_labels, all_preds)

    metrics = {
        "model": "resnet18",  # change per model
        "cv_mean_acc": float(np.mean(fold_results)),
        "cv_std_acc": float(np.std(fold_results)),
        "test_macro_f1": float(macro_f1),
        "test_weighted_f1": float(weighted_f1),
        "test_kappa": float(kappa)
    }

    with open("metrics_resnet18.json", "w") as f:
      json.dump(metrics, f, indent=4)

    print("\n" + report)
    print(f"  Macro F1    : {macro_f1:.4f}")
    print(f"  Weighted F1 : {weighted_f1:.4f}")
    print(f"  Cohen Kappa : {kappa:.4f}")
    report_filename = CONFIG['save_path'].replace('.pth', '_report.txt')
    with open(report_filename, 'w') as f:
      f.write(report)
      f.write(f"\nMacro F1    : {macro_f1:.4f}\n")
      f.write(f"Weighted F1 : {weighted_f1:.4f}\n")
      f.write(f"Cohen Kappa : {kappa:.4f}\n")
    print(f"📄 Classification report saved to: {report_filename}")
    plot_confusion_matrix(all_labels, all_preds, classes)

    # ----------------------------
    # 7. SAVE FINAL MODEL
    # ----------------------------
    final_model.to('cpu')
    torch.save({
        'model_state_dict': best_final_wts,      # ← full trainval model
        'class_names':      classes,
        'num_classes':      num_classes,
        'fold_results':     fold_results,         # CV evidence for the paper
        'cv_mean_acc':      float(np.mean(fold_results)),
        'cv_std_acc':       float(np.std(fold_results)),
        'best_val_acc':     best_overall_acc,     # best CV fold acc (for paper)
        'config':           CONFIG,
    }, CONFIG['save_path'])
    print(f"\n💾 Final model saved to: {CONFIG['save_path']}")

    results = {
        "model": "resnet18",
        "fold_acc": fold_results,
        "mean_acc": float(np.mean(fold_results)),
        "std_acc": float(np.std(fold_results))
    }

    with open("results_resnet18.json", "w") as f:
      json.dump(results, f, indent=4)

if __name__ == "__main__":
    DATASET_PATH = "dataset"
    train_model(DATASET_PATH)